# Generated by Django 4.2.9 on 2026-05-09 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_meeting_global_camera_off_meeting_global_mute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cameras', '0009_cameralog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='uploaded_lectures/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='lecture_thumbnails/')),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to='meetings.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Video',
                'verbose_name_plural': 'Uploaded Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
