# Generated by Django 4.2.9 on 2026-06-06 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import video_editing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('edited_video', models.FileField(blank=True, null=True, upload_to=video_editing.models.edited_video_upload_path)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to=settings.AUTH_USER_MODEL)),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoEditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('split', 'Split Video'), ('mute', 'Mute Audio'), ('unmute', 'Unmute Audio'), ('trim', 'Trim Video'), ('crop', 'Crop Video'), ('rotate', 'Rotate Video')], max_length=20)),
                ('parameters', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='video_editing.videoeditsession')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
