# Generated by Django 4.2.9 on 2026-06-06 10:53

from django.db import migrations, models
import video_editing.models


class Migration(migrations.Migration):

    dependencies = [
        ('video_editing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoeditaction',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=video_editing.models.audio_upload_path),
        ),
        migrations.AlterField(
            model_name='videoeditaction',
            name='action_type',
            field=models.CharField(choices=[('split', 'Split Video'), ('mute', 'Mute Audio'), ('unmute', 'Unmute Audio'), ('trim', 'Trim Video'), ('crop', 'Crop Video'), ('rotate', 'Rotate Video'), ('add_text', 'Add Text Overlay'), ('add_audio', 'Add/Overlay Audio'), ('replace_audio', 'Replace Audio')], max_length=20),
        ),
    ]
