"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import asyncio
from dotenv import load_dotenv

# Set the event loop policy for Windows to support subprocesses in asyncio
# In Python 3.14+, this might be the default, but we ensure it's applied
# to avoid NotImplementedError in Daphne/Channels
if sys.platform == 'win32':
    try:
        if hasattr(asyncio, 'WindowsProactorEventLoopPolicy'):
            asyncio.set_event_loop_policy(asyncio.WindowsProactorEventLoopPolicy())
    except Exception:
        pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-@j!l-9t=qs!b&lkynb=zq$-h3f9d(_nm!hvctk$9ij()0kaja%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allow any host in production/docker to make IP-based access easier
ALLOWED_HOSTS = ['*']

# Security Settings for Production
if not DEBUG:
    SECURE_SSL_REDIRECT = False # Set to True only if you have SSL/HTTPS configured
    SESSION_COOKIE_SECURE = False # Set to True only if using HTTPS
    CSRF_COOKIE_SECURE = False # Set to True only if using HTTPS
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 0 # Only enable if using HTTPS
    X_FRAME_OPTIONS = 'SAMEORIGIN' # Changed from DENY to allow some camera features if needed
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    X_FRAME_OPTIONS = 'SAMEORIGIN'

# Read CSRF trusted origins from environment variable
CSRF_TRUSTED_ORIGINS = []
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]

# Always add these defaults for local development
DEFAULT_CSRF_ORIGINS = [
    'http://localhost',
    'http://localhost:8000',
    'http://localhost:8002',
    'http://localhost:8003',
    'http://localhost:8080',
    'https://localhost',
    'https://localhost:8000',
    'https://localhost:8002',
    'https://localhost:8003',
    'https://localhost:8080',
    'http://127.0.0.1',
    'http://127.0.0.1:8000',
    'http://127.0.0.1:8002',
    'http://127.0.0.1:8003',
    'http://127.0.0.1:8080',
    'https://127.0.0.1',
    'https://127.0.0.1:8000',
    'https://127.0.0.1:8002',
    'https://127.0.0.1:8003',
    'https://127.0.0.1:8080',
    'http://10.7.11.141',
    'https://10.7.11.141',
    'http://192.168.1.100',
    'http://192.168.1.100:8080',
    'https://192.168.1.100',
    'https://192.168.1.100:8080',
]
for origin in DEFAULT_CSRF_ORIGINS:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# For extra flexibility, allow wildcard host
CSRF_ALLOW_WILDCARD_HOST = True

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'common',  # New: Common utilities, mixins, tags
    'accounts',
    'cameras',  # RTSP Camera management
    'mobile_cameras',  # Mobile Camera management (IP Webcam, DroidCam)
    'meetings',
    'attendance',  # Face Recognition Attendance System
    'videos',  # New: Video streaming app!
    'video_editing',  # New: Video editing app!
    'django_extensions',  # For HTTPS development server
    'compressor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

try:
    import whitenoise
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass

MIDDLEWARE.extend([
    'school_project.middleware.DatabaseErrorMiddleware',  # Handle database locked errors
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
])

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.timestamp',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'
ASGI_APPLICATION = 'school_project.asgi.application'

# Channels Configuration
# We use RedisChannelLayer when running in Docker/Linux (where Redis 5+ is available)
# On Windows, we force InMemoryChannelLayer to avoid "unknown command 'BZPOPMIN'" 
# which occurs with older Windows Redis versions (3.x).
REDIS_URL = os.environ.get('REDIS_URL')

# Use Redis channel layer when REDIS_URL is set.
# In Docker (Linux) always use Redis. On Windows dev without Redis, fall back to InMemory.
_use_redis_channels = bool(REDIS_URL) and (sys.platform != 'win32' or os.environ.get('FORCE_REDIS_CHANNELS'))

if _use_redis_channels:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    # Windows dev without Redis — InMemoryChannelLayer (single process only)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_DIR = BASE_DIR / 'database'
DATABASE_DIR.mkdir(parents=True, exist_ok=True)  # Create database directory if doesn't exist

if os.environ.get('DATABASE_URL'):
    try:
        import dj_database_url
        DATABASES = {
            'default': dj_database_url.config(conn_max_age=600)
        }
    except ImportError:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': DATABASE_DIR / 'db.sqlite3',
                'OPTIONS': {
                    'timeout': 30,  # Wait up to 30 seconds for database lock
                    'check_same_thread': False,  # Allow multi-threaded access
                },
            }
        }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': DATABASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,  # Wait up to 30 seconds for database lock
                'check_same_thread': False,  # Allow multi-threaded access
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# Use WhiteNoise to serve static files with compression and caching
try:
    import whitenoise
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
except ImportError:
    pass
COMPRESS_ENABLED = True
COMPRESS_URL = '/static/'
COMPRESS_STORAGE = 'compressor.storage.CompressorFileStorage'
COMPRESS_ROOT = STATIC_ROOT

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = DATABASE_DIR / 'media'
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)  # Ensure media directory exists

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'student_dashboard'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'cameras': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Celery Configuration Options
# Celery supports Redis 3.x, so we can keep using it for background tasks.
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# LiveKit Settings
LIVEKIT_URL = os.environ.get('LIVEKIT_URL', 'ws://localhost:8000/livekit-proxy')
LIVEKIT_INTERNAL_URL = os.environ.get('LIVEKIT_INTERNAL_URL', 'ws://localhost:7880')
LIVEKIT_INTERNAL_HTTP_URL = os.environ.get('LIVEKIT_INTERNAL_HTTP_URL', 'http://localhost:7880')
LIVEKIT_API_KEY = os.environ.get('LIVEKIT_API_KEY', 'devkey')
LIVEKIT_API_SECRET = os.environ.get('LIVEKIT_API_SECRET', 'devsecret_must_be_32_characters_long_1234')

# Camera Head Count Settings
HEAD_COUNT_INTERVAL = 30
ATTENTION_THRESHOLD = 0.6
EMOTION_LOGGING_ENABLED = True

# Camera Service URL (internal, server-side only)
# In Docker: uses service name via CAMERA_SERVICE_URL env var
# In dev: falls back to localhost:8001
CAMERA_SERVICE_URL = os.environ.get('CAMERA_SERVICE_URL', 'http://localhost:8003')

# Generate a key once: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Then add it to .env as FACE_ENCRYPTION_KEY=<your-key>
FACE_ENCRYPTION_KEY = os.environ.get('FACE_ENCRYPTION_KEY', 'zl-c_61OHA9zX1LiIJ9cinnXJOXQhRkBEIs2JvJRh6Y=')
# L2 distance threshold: 0 = identical, 1 = completely different
# 0.50 is stricter than the face_recognition default of 0.60
FACE_MATCH_THRESHOLD = float(os.environ.get('FACE_MATCH_THRESHOLD', '0.50'))
# Cumulative verified seconds before attendance is recorded
FACE_PRESENCE_DURATION = int(os.environ.get('FACE_PRESENCE_DURATION', '30'))
