"""
Django settings for school_project project.

Generated by 'django-admin startproject' using Django 4.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'), override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-@j!l-9t=qs!b&lkynb=zq$-h3f9d(_nm!hvctk$9ij()0kaja%')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,*').split(',')

# Disable SSL redirect for development (enable in production)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = [
    'https://localhost',
    'https://localhost:8443',
    'https://127.0.0.1',
    'https://127.0.0.1:8443',
    'https://10.7.32.175',
    'https://10.7.32.175:8443',
    'https://10.17.2.47',
    'https://10.17.2.47:8443',
    'https://*.ngrok.io',
    'https://*.ngrok-free.app',
    'https://*.ngrok-free.dev',
]
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_HSTS_SECONDS = 0

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'accounts',
    'pages',
    'cameras',  # RTSP Camera management
    'mobile_cameras',  # Mobile Camera management (IP Webcam, DroidCam)
    'meetings',
    'attendance',  # Face Recognition Attendance System
    'django_browser_reload',
    'django_extensions',  # For HTTPS development server
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'school_project.middleware.RemoveUnsupportedSecurityHeadersMiddleware',  # Strip COOP/COEP on HTTP
    'school_project.middleware.DatabaseErrorMiddleware',  # Handle database locked errors
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'school_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.timestamp',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_project.wsgi.application'
ASGI_APPLICATION = 'school_project.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    # No Redis available — use in-memory channel layer (single-process only)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL', '')

if DATABASE_URL:
    # PostgreSQL (used in Docker / production)
    import urllib.parse as _up
    _u = _up.urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     _u.path.lstrip('/'),
            'USER':     _u.username,
            'PASSWORD': _u.password,
            'HOST':     _u.hostname,
            'PORT':     str(_u.port or 5432),
        }
    }
else:
    # SQLite (local dev — no extra setup needed)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            'OPTIONS': {
                'timeout': 30,
                'check_same_thread': False,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

COMPRESS_ENABLED = False
COMPRESS_URL = '/static/'
COMPRESS_STORAGE = 'compressor.storage.CompressorFileStorage'
COMPRESS_ROOT = STATIC_ROOT

# Media files (uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

LOGIN_URL = 'login'
LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'student_dashboard'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'clean': {
            'format': '[{levelname}] {asctime} {module}: {message}',
            'style': '{',
            'datefmt': '%H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'clean',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # ── App loggers (keep these) ──────────────────────────────────────
        'cameras': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'attendance': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'meetings': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },

        # ── Django internals — only errors ────────────────────────────────
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Silence 404 warnings completely (they flood the terminal)
        'django.request': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        # Silence routine DB queries
        'django.db.backends': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },

        # ── Daphne / ASGI — silence per-request access lines ─────────────
        'daphne.access': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
        'daphne': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },

        # ── Channels ─────────────────────────────────────────────────────
        'channels': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },

        # ── Third-party noise ─────────────────────────────────────────────
        'asyncio': {
            'handlers': ['null'],
            'level': 'CRITICAL',
            'propagate': False,
        },
    },
    # Root logger: only show WARNING+ from anything not listed above
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}

# Celery Configuration Options
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'memory://')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'cache+memory://')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# ─── LiveKit SFU ────────────────────────────────────────────────────────────
# LIVEKIT_URL: what the *browser* connects to.
# When running behind ngrok, set this to your ngrok URL + /livekit-proxy
# e.g.  wss://xxxx.ngrok-free.app/livekit-proxy
# The proxy in asgi.py forwards it to ws://localhost:7880 internally.
LIVEKIT_URL = os.environ.get('LIVEKIT_URL', 'ws://localhost:7880')
LIVEKIT_API_KEY = os.environ.get('LIVEKIT_API_KEY', 'devkey')
LIVEKIT_API_SECRET = os.environ.get('LIVEKIT_API_SECRET', 'devsecret_must_be_32_characters_long_1234')
# Generate a key once: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Then add it to .env as FACE_ENCRYPTION_KEY=<your-key>
FACE_ENCRYPTION_KEY = os.environ.get('FACE_ENCRYPTION_KEY', '')
# L2 distance threshold: 0 = identical, 1 = completely different
# 0.50 is stricter than the face_recognition default of 0.60
FACE_MATCH_THRESHOLD = float(os.environ.get('FACE_MATCH_THRESHOLD', '0.50'))
# Cumulative verified seconds before attendance is recorded
FACE_PRESENCE_DURATION = int(os.environ.get('FACE_PRESENCE_DURATION', '30'))
