# Generated by Django 4.2.9 on 2026-03-17 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_engagementreport_studentengagementsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='studentengagementsnapshot',
            new_name='attendance__meeting_59dfee_idx',
            old_name='attendance__meeting_7e3c2a_idx',
        ),
        migrations.AddField(
            model_name='faceresetrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_face_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faceresetrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_reset_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
